// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    partial class ApiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("backend.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = "cGFzczE=",
                            Username = "user1"
                        },
                        new
                        {
                            Id = 2,
                            PasswordHash = "cGFzczI=",
                            Username = "user2"
                        },
                        new
                        {
                            Id = 3,
                            PasswordHash = "cGFzczM=",
                            Username = "user3"
                        },
                        new
                        {
                            Id = 4,
                            PasswordHash = "cGFzczQ=",
                            Username = "user4"
                        },
                        new
                        {
                            Id = 5,
                            PasswordHash = "cGFzczU=",
                            Username = "user5"
                        },
                        new
                        {
                            Id = 6,
                            PasswordHash = "cGFzczY=",
                            Username = "user6"
                        },
                        new
                        {
                            Id = 7,
                            PasswordHash = "cGFzczc=",
                            Username = "user7"
                        },
                        new
                        {
                            Id = 8,
                            PasswordHash = "cGFzczg=",
                            Username = "user8"
                        },
                        new
                        {
                            Id = 9,
                            PasswordHash = "cGFzczk=",
                            Username = "user9"
                        },
                        new
                        {
                            Id = 10,
                            PasswordHash = "cGFzczEw",
                            Username = "user10"
                        },
                        new
                        {
                            Id = 11,
                            PasswordHash = "cGFzczEx",
                            Username = "user11"
                        },
                        new
                        {
                            Id = 12,
                            PasswordHash = "cGFzczEy",
                            Username = "user12"
                        },
                        new
                        {
                            Id = 13,
                            PasswordHash = "cGFzczEz",
                            Username = "user13"
                        },
                        new
                        {
                            Id = 14,
                            PasswordHash = "cGFzczE0",
                            Username = "user14"
                        },
                        new
                        {
                            Id = 15,
                            PasswordHash = "cGFzczE1",
                            Username = "user15"
                        },
                        new
                        {
                            Id = 16,
                            PasswordHash = "cGFzczE2",
                            Username = "user16"
                        },
                        new
                        {
                            Id = 17,
                            PasswordHash = "cGFzczE3",
                            Username = "user17"
                        },
                        new
                        {
                            Id = 18,
                            PasswordHash = "cGFzczE4",
                            Username = "user18"
                        },
                        new
                        {
                            Id = 19,
                            PasswordHash = "cGFzczE5",
                            Username = "user19"
                        },
                        new
                        {
                            Id = 20,
                            PasswordHash = "cGFzczIw",
                            Username = "user20"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
