// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    partial class ApiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("backend.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Description for product 1",
                            Name = "Product 1",
                            Price = 10m,
                            Stock = 2
                        },
                        new
                        {
                            Id = 2,
                            Description = "Description for product 2",
                            Name = "Product 2",
                            Price = 20m,
                            Stock = 4
                        },
                        new
                        {
                            Id = 3,
                            Description = "Description for product 3",
                            Name = "Product 3",
                            Price = 30m,
                            Stock = 6
                        },
                        new
                        {
                            Id = 4,
                            Description = "Description for product 4",
                            Name = "Product 4",
                            Price = 40m,
                            Stock = 8
                        },
                        new
                        {
                            Id = 5,
                            Description = "Description for product 5",
                            Name = "Product 5",
                            Price = 50m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 6,
                            Description = "Description for product 6",
                            Name = "Product 6",
                            Price = 60m,
                            Stock = 12
                        },
                        new
                        {
                            Id = 7,
                            Description = "Description for product 7",
                            Name = "Product 7",
                            Price = 70m,
                            Stock = 14
                        },
                        new
                        {
                            Id = 8,
                            Description = "Description for product 8",
                            Name = "Product 8",
                            Price = 80m,
                            Stock = 16
                        },
                        new
                        {
                            Id = 9,
                            Description = "Description for product 9",
                            Name = "Product 9",
                            Price = 90m,
                            Stock = 18
                        },
                        new
                        {
                            Id = 10,
                            Description = "Description for product 10",
                            Name = "Product 10",
                            Price = 100m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 11,
                            Description = "Description for product 11",
                            Name = "Product 11",
                            Price = 110m,
                            Stock = 22
                        },
                        new
                        {
                            Id = 12,
                            Description = "Description for product 12",
                            Name = "Product 12",
                            Price = 120m,
                            Stock = 24
                        },
                        new
                        {
                            Id = 13,
                            Description = "Description for product 13",
                            Name = "Product 13",
                            Price = 130m,
                            Stock = 26
                        },
                        new
                        {
                            Id = 14,
                            Description = "Description for product 14",
                            Name = "Product 14",
                            Price = 140m,
                            Stock = 28
                        },
                        new
                        {
                            Id = 15,
                            Description = "Description for product 15",
                            Name = "Product 15",
                            Price = 150m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 16,
                            Description = "Description for product 16",
                            Name = "Product 16",
                            Price = 160m,
                            Stock = 32
                        },
                        new
                        {
                            Id = 17,
                            Description = "Description for product 17",
                            Name = "Product 17",
                            Price = 170m,
                            Stock = 34
                        },
                        new
                        {
                            Id = 18,
                            Description = "Description for product 18",
                            Name = "Product 18",
                            Price = 180m,
                            Stock = 36
                        },
                        new
                        {
                            Id = 19,
                            Description = "Description for product 19",
                            Name = "Product 19",
                            Price = 190m,
                            Stock = 38
                        },
                        new
                        {
                            Id = 20,
                            Description = "Description for product 20",
                            Name = "Product 20",
                            Price = 200m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 21,
                            Description = "Description for product 21",
                            Name = "Product 21",
                            Price = 210m,
                            Stock = 42
                        },
                        new
                        {
                            Id = 22,
                            Description = "Description for product 22",
                            Name = "Product 22",
                            Price = 220m,
                            Stock = 44
                        },
                        new
                        {
                            Id = 23,
                            Description = "Description for product 23",
                            Name = "Product 23",
                            Price = 230m,
                            Stock = 46
                        },
                        new
                        {
                            Id = 24,
                            Description = "Description for product 24",
                            Name = "Product 24",
                            Price = 240m,
                            Stock = 48
                        },
                        new
                        {
                            Id = 25,
                            Description = "Description for product 25",
                            Name = "Product 25",
                            Price = 250m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 26,
                            Description = "Description for product 26",
                            Name = "Product 26",
                            Price = 260m,
                            Stock = 52
                        },
                        new
                        {
                            Id = 27,
                            Description = "Description for product 27",
                            Name = "Product 27",
                            Price = 270m,
                            Stock = 54
                        },
                        new
                        {
                            Id = 28,
                            Description = "Description for product 28",
                            Name = "Product 28",
                            Price = 280m,
                            Stock = 56
                        },
                        new
                        {
                            Id = 29,
                            Description = "Description for product 29",
                            Name = "Product 29",
                            Price = 290m,
                            Stock = 58
                        },
                        new
                        {
                            Id = 30,
                            Description = "Description for product 30",
                            Name = "Product 30",
                            Price = 300m,
                            Stock = 60
                        },
                        new
                        {
                            Id = 31,
                            Description = "Description for product 31",
                            Name = "Product 31",
                            Price = 310m,
                            Stock = 62
                        },
                        new
                        {
                            Id = 32,
                            Description = "Description for product 32",
                            Name = "Product 32",
                            Price = 320m,
                            Stock = 64
                        },
                        new
                        {
                            Id = 33,
                            Description = "Description for product 33",
                            Name = "Product 33",
                            Price = 330m,
                            Stock = 66
                        },
                        new
                        {
                            Id = 34,
                            Description = "Description for product 34",
                            Name = "Product 34",
                            Price = 340m,
                            Stock = 68
                        },
                        new
                        {
                            Id = 35,
                            Description = "Description for product 35",
                            Name = "Product 35",
                            Price = 350m,
                            Stock = 70
                        },
                        new
                        {
                            Id = 36,
                            Description = "Description for product 36",
                            Name = "Product 36",
                            Price = 360m,
                            Stock = 72
                        },
                        new
                        {
                            Id = 37,
                            Description = "Description for product 37",
                            Name = "Product 37",
                            Price = 370m,
                            Stock = 74
                        },
                        new
                        {
                            Id = 38,
                            Description = "Description for product 38",
                            Name = "Product 38",
                            Price = 380m,
                            Stock = 76
                        },
                        new
                        {
                            Id = 39,
                            Description = "Description for product 39",
                            Name = "Product 39",
                            Price = 390m,
                            Stock = 78
                        },
                        new
                        {
                            Id = 40,
                            Description = "Description for product 40",
                            Name = "Product 40",
                            Price = 400m,
                            Stock = 80
                        },
                        new
                        {
                            Id = 41,
                            Description = "Description for product 41",
                            Name = "Product 41",
                            Price = 410m,
                            Stock = 82
                        },
                        new
                        {
                            Id = 42,
                            Description = "Description for product 42",
                            Name = "Product 42",
                            Price = 420m,
                            Stock = 84
                        },
                        new
                        {
                            Id = 43,
                            Description = "Description for product 43",
                            Name = "Product 43",
                            Price = 430m,
                            Stock = 86
                        },
                        new
                        {
                            Id = 44,
                            Description = "Description for product 44",
                            Name = "Product 44",
                            Price = 440m,
                            Stock = 88
                        },
                        new
                        {
                            Id = 45,
                            Description = "Description for product 45",
                            Name = "Product 45",
                            Price = 450m,
                            Stock = 90
                        },
                        new
                        {
                            Id = 46,
                            Description = "Description for product 46",
                            Name = "Product 46",
                            Price = 460m,
                            Stock = 92
                        },
                        new
                        {
                            Id = 47,
                            Description = "Description for product 47",
                            Name = "Product 47",
                            Price = 470m,
                            Stock = 94
                        },
                        new
                        {
                            Id = 48,
                            Description = "Description for product 48",
                            Name = "Product 48",
                            Price = 480m,
                            Stock = 96
                        },
                        new
                        {
                            Id = 49,
                            Description = "Description for product 49",
                            Name = "Product 49",
                            Price = 490m,
                            Stock = 98
                        },
                        new
                        {
                            Id = 50,
                            Description = "Description for product 50",
                            Name = "Product 50",
                            Price = 500m,
                            Stock = 100
                        });
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "pass1",
                            Username = "user1"
                        },
                        new
                        {
                            Id = 2,
                            Password = "pass2",
                            Username = "user2"
                        },
                        new
                        {
                            Id = 3,
                            Password = "pass3",
                            Username = "user3"
                        },
                        new
                        {
                            Id = 4,
                            Password = "pass4",
                            Username = "user4"
                        },
                        new
                        {
                            Id = 5,
                            Password = "pass5",
                            Username = "user5"
                        },
                        new
                        {
                            Id = 6,
                            Password = "pass6",
                            Username = "user6"
                        },
                        new
                        {
                            Id = 7,
                            Password = "pass7",
                            Username = "user7"
                        },
                        new
                        {
                            Id = 8,
                            Password = "pass8",
                            Username = "user8"
                        },
                        new
                        {
                            Id = 9,
                            Password = "pass9",
                            Username = "user9"
                        },
                        new
                        {
                            Id = 10,
                            Password = "pass10",
                            Username = "user10"
                        },
                        new
                        {
                            Id = 11,
                            Password = "pass11",
                            Username = "user11"
                        },
                        new
                        {
                            Id = 12,
                            Password = "pass12",
                            Username = "user12"
                        },
                        new
                        {
                            Id = 13,
                            Password = "pass13",
                            Username = "user13"
                        },
                        new
                        {
                            Id = 14,
                            Password = "pass14",
                            Username = "user14"
                        },
                        new
                        {
                            Id = 15,
                            Password = "pass15",
                            Username = "user15"
                        },
                        new
                        {
                            Id = 16,
                            Password = "pass16",
                            Username = "user16"
                        },
                        new
                        {
                            Id = 17,
                            Password = "pass17",
                            Username = "user17"
                        },
                        new
                        {
                            Id = 18,
                            Password = "pass18",
                            Username = "user18"
                        },
                        new
                        {
                            Id = 19,
                            Password = "pass19",
                            Username = "user19"
                        },
                        new
                        {
                            Id = 20,
                            Password = "pass20",
                            Username = "user20"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
